// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // 资料-Docusaurus
  docusaurus: [
    {
      type: 'category',
      label: 'Docusaurus',
      collapsible: false,
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'Docusaurus'}],
    },
  ],
  ai: [
    {
      type: 'category',
      label: 'AI',
      collapsible: false,
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'AI'}],
    },
  ],
};

export default sidebars;
